name: benchmark

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: 1
  NUGET_XMLDOC_MODE: skip
  TERM: xterm

on:
  push:
    branches:
      - main
      - dotnet-vnext
      - dotnet-nightly
    paths-ignore:
      - '**/*.gitattributes'
      - '**/*.gitignore'
      - '**/*.md'
  workflow_dispatch:

permissions: {}

jobs:
  benchmark:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      id-token: write

    steps:

    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        filter: 'tree:0'
        persist-credentials: false
        show-progress: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

    - name: Setup Node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '24.x'

    - name: Run benchmarks
      shell: pwsh
      run: ./benchmark.ps1

    - name: Publish BenchmarkDotNet artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: ${{ !cancelled() }}
      with:
        name: artifacts
        path: ./BenchmarkDotNet.Artifacts/results/*
        if-no-files-found: error

    - name: Get repository name
      id: get-repo-name
      shell: pwsh
      run: |
        $repoName = ${env:GITHUB_REPOSITORY}.Split("/")[-1]
        "repo-name=${repoName}" >> ${env:GITHUB_OUTPUT}

    - name: Get GitHub token
      id: get-github-token
      if: github.event.repository.fork == false
      uses: martincostello/github-automation/actions/get-github-token@18237c275f9a773966e3e52dcabe5e7e559a9786 # get-github-token/v4.3.1
      with:
        profile-name: benchmarks

    - name: Publish results
      uses: martincostello/benchmarkdotnet-results-publisher@b1e7cf14565f479f7d7628c89ca3936142fa6d67 # v2.0.4
      if: github.event.repository.fork == false
      with:
        branch: ${{ github.ref_name }}
        comment-on-threshold: true
        name: LondonTravel.Site
        output-file-path: '${{ steps.get-repo-name.outputs.repo-name }}/data.json'
        repo: '${{ github.repository_owner }}/benchmarks'
        repo-token: ${{ steps.get-github-token.outputs.token }}

    - name: Output summary
      shell: pwsh
      env:
        REPO_NAME: ${{ steps.get-repo-name.outputs.repo-name }}
      run: |
        $summary += "`n`n"
        $summary += "View benchmark results history [here](https://benchmarks.martincostello.com/?repo=${env:REPO_NAME}&branch=${env:GITHUB_REF_NAME})."
        $summary >> ${env:GITHUB_STEP_SUMMARY}
