name: container-scan

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions: {}

env:
  FORCE_COLOR: 3
  TERM: xterm

jobs:
  scan-image:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Configure Trivvy
        id: configure
        shell: pwsh
        run: |
          $registry = "${env:GITHUB_REPOSITORY_OWNER}.azurecr.io"
          $image = "${registry}/${env:GITHUB_REPOSITORY}:latest".ToLowerInvariant()
          "container-image=${image}" >> ${env:GITHUB_OUTPUT}

      - name: Run Trivy (SARIF)
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # 0.21.0
        env:
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
        with:
          image-ref: ${{ steps.configure.outputs.container-image }}
          format: 'sarif'
          ignore-unfixed: true
          limit-severities-for-sarif: true
          output: 'trivy.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@9fdb3e49720b44c48891d036bb502feb25684276 # v3.25.6
        if: ${{ !cancelled() }}
        with:
          sarif_file: 'trivy.sarif'

      - name: Run Trivy (Table)
        uses: aquasecurity/trivy-action@fd25fed6972e341ff0007ddb61f77e88103953c2 # 0.21.0
        env:
          TRIVY_USERNAME: ${{ secrets.TRIVY_USERNAME }}
          TRIVY_PASSWORD: ${{ secrets.TRIVY_PASSWORD }}
        with:
          image-ref: ${{ steps.configure.outputs.container-image }}
          format: 'table'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
